#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../../../
echo "Running script from: $(pwd)"

# backup existing Vagrantfile
if [ -f Vagrantfile ]; then
    VERSION=$(date +"%Y%m%d_%H%M%S")
    mv Vagrantfile{,.bak.$VERSION}
    echo "Backing up current Vagrantfile to: Vagrantfile.$VERSION"
fi

# copy correct Vagrantfile in place
ln -s vagrantfiles/datastax/cornerstone Vagrantfile
ls -alh Vagrantfile

echo "Setting credentials using: ./set_credentials.sh"
source set_credentials.sh || exit 1

# clear envars
unset SEEDS GATHER_IPS DEMO_HOST WEB_PORT

export NODE=0; vagrant up singlenode${NODE}
#export NODE=1; vagrant up singlenode${NODE}
#export NODE=2; vagrant up singlenode${NODE}

# collect DSE seeds
vagrant awsinfo -m singlenode${NODE} -k public_ip

# gather web ports
export WEB_PORT=1
DEMO_PORT=$(vagrant provision singlenode${NODE} | grep WEB_PORT | awk '{print $4}')
unset WEB_PORT

# display urls
echo -e "Demo address: \n    http://$(vagrant awsinfo -m singlenode${NODE} -k public_ip):${DEMO_PORT}"
