#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../../../
echo "Running script from: $(pwd)"

# backup existing Vagrantfile
if [ -f Vagrantfile ] || [ -L Vagrantfile ]; then
    VERSION=$(date +"%Y%m%d_%H%M%S")
    mv Vagrantfile{,.bak.$VERSION}
    echo "Backing up current Vagrantfile to: Vagrantfile.$VERSION"
fi

# copy correct Vagrantfile in place
ln -s vagrantfiles/datastax/cornerstone Vagrantfile
ls -alh Vagrantfile

echo "Setting credentials using: ./set_credentials.sh"
source set_credentials.sh || exit 1

# clear SEEDS
unset SEEDS

# start machines, install, do not provision
vagrant --provider aws up dse0 dse1 dse2 opscenter demo

# collect DSE seeds
DSE0=vagrant awsinfo -m dse0 -k private_ip
DSE1=vagrant awsinfo -m dse1 -k private_ip
DSE2=vagrant awsinfo -m dse2 -k private_ip
SEEDS=$DSE0,$DSE1,$DSE2

# configure, start
# TODO: Not setting proper variables
vagrant --provision dse0 dse1 dse2 opscenter demo
