#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../../../
echo "Running script from: $(pwd)"

# backup existing Vagrantfile
if [ -f Vagrantfile ]; then
    VERSION=$(date +"%Y%m%d_%H%M%S")
    mv Vagrantfile{,.bak.$VERSION}
    echo "Backing up current Vagrantfile to: Vagrantfile.$VERSION"
fi

# copy correct Vagrantfile in place
ln -s vagrantfiles/datastax/cornerstone Vagrantfile
ls -alh Vagrantfile

echo "Setting credentials using: ./set_credentials.sh"
source set_credentials.sh || exit 1

# clear envars
unset SEEDS GATHER_IPS DEMO_HOST WEB_PORT

vagrant up singlenode0
#vagrant up singlenode1
#vagrant up singlenode2

# collect DSE seeds
vagrant awsinfo -m singlenode0 -k public_ip
#vagrant awsinfo -m singlenode1 -k public_ip
#vagrant awsinfo -m singlenode2 -k public_ip

# gather web ports
export WEB_PORT=1
DEMO_PORT=$(vagrant provision singlenode0 | grep WEB_PORT | awk '{print $4}')
unset WEB_PORT

# display urls
echo -e "Demo address: \n    http://$(vagrant awsinfo -m singlenode0 -k public_ip):${DEMO_PORT}"
