#!/bin/bash

for file in $(find /cornerstone/vagrant -type f)
do
   ls $file
   filename=$(basename $file)
   sed -i -e "s|FILENAME=.*|FILENAME=${filename}|g" $file
done

files=$(find vagrant -type f | grep _v1.sh)
for file in $files
do
    new=$(echo $file | sed -e 's|v1|v2|')
    mv $file $new
done
