#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../../../
echo "Running script from: $(pwd)"

# backup existing Vagrantfile
if [ -f Vagrantfile ]; then
    VERSION=$(date +"%Y%m%d_%H%M%S")
    mv Vagrantfile{,.bak.$VERSION}
    echo "Backing up current Vagrantfile to: Vagrantfile.$VERSION"
fi

# copy correct Vagrantfile in place
ln -s vagrantfiles/datastax/ticker Vagrantfile
ls -alh Vagrantfile

echo "Setting credentials using: ./set_credentials.sh"
source set_credentials.sh || exit 1

vagrant up --provider=azure singlenode

# gather web ports
export WEB_PORT=1
DEMO_PORT=$(vagrant provision singlenode | grep WEB_PORT | awk '{print $4}')
unset WEB_PORT

# display urls
DEMO_PUBLIC_HOST=$(vagrant ssh-config singlenode | grep HostName | awk '{print $2}')
echo -e "Demo address: \n    http://${DEMO_PUBLIC_HOST}:${DEMO_PORT}"
