#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../../../
echo "Running script from: $(pwd)"

# backup existing Vagrantfile
VERSION=$(date +"%Y%m%d_%H%M%S")
mkdir -p logs/${VERSION}
if [ -f Vagrantfile ] || [ -L Vagrantfile ]; then
    mv Vagrantfile{,.bak.$VERSION}
    echo "Backing up current Vagrantfile to: Vagrantfile.$VERSION"
fi

# copy correct Vagrantfile in place
ln -s vagrantfiles/datastax/ticker Vagrantfile
ls -alh Vagrantfile

echo "Setting credentials using: ./set_credentials.sh"
source set_credentials.sh || exit 1

# clear envars
unset SEEDS GATHER_IPS OPSCENTER_HOST DEMO_HOST WEB_PORT SPARK SOLR

time (
    # start machines
    export GATHER_IPS=1
    vagrant up --provider azure dse0 dse1 dse2 dse3 dse4 dse5 dse6 dse7 dse8 dse9 opscenter demo | tee logs/${VERSION}/up.log
    unset GATHER_IPS
)

time (
    # install, do not provision
    vagrant provision dse0 | tee logs/${VERSION}/dse0.log &
    vagrant provision dse1 | tee logs/${VERSION}/dse1.log &
    vagrant provision dse2 | tee logs/${VERSION}/dse2.log &
    vagrant provision dse3 | tee logs/${VERSION}/dse3.log &
    vagrant provision dse4 | tee logs/${VERSION}/dse4.log &
    vagrant provision dse5 | tee logs/${VERSION}/dse5.log &
    vagrant provision dse6 | tee logs/${VERSION}/dse6.log &
    vagrant provision dse7 | tee logs/${VERSION}/dse7.log &
    vagrant provision dse8 | tee logs/${VERSION}/dse8.log &
    vagrant provision dse9 | tee logs/${VERSION}/dse9.log &
    vagrant provision opscenter | tee logs/${VERSION}/opscenter.log &
    vagrant provision demo | tee logs/${VERSION}/demo.log &

    jobs
    wait
)

# collect IPs
export GATHER_IPS=1
DSE0=$(vagrant provision dse0 | grep GATHER_IPS | awk '{print $4}')
DSE1=$(vagrant provision dse1 | grep GATHER_IPS | awk '{print $4}')
DSE2=$(vagrant provision dse2 | grep GATHER_IPS | awk '{print $4}')
DSE3=$(vagrant provision dse3 | grep GATHER_IPS | awk '{print $4}')
DSE4=$(vagrant provision dse4 | grep GATHER_IPS | awk '{print $4}')

DSE5=$(vagrant provision dse5 | grep GATHER_IPS | awk '{print $4}')
DSE6=$(vagrant provision dse6 | grep GATHER_IPS | awk '{print $4}')
DSE7=$(vagrant provision dse7 | grep GATHER_IPS | awk '{print $4}')
DSE8=$(vagrant provision dse8 | grep GATHER_IPS | awk '{print $4}')
DSE9=$(vagrant provision dse9 | grep GATHER_IPS | awk '{print $4}')

export OPSCENTER_HOST=$(vagrant provision opscenter | grep GATHER_IPS | awk '{print $4}')
export DEMO_HOST=$(vagrant provision demo | grep GATHER_IPS | awk '{print $4}')
unset GATHER_IPS

export SEEDS=$DSE0,$DSE1,$DSE2,$DSE3,$DSE4,$DSE5,$DSE6,$DSE7,$DSE8,$DSE9
export SOLR_NODE=$DSE5

# finish configuration, start
export SPARK=1
    vagrant provision dse0 | tee -a logs/${VERSION}/dse0.log
    vagrant provision dse1 | tee -a logs/${VERSION}/dse1.log &
    vagrant provision dse2 | tee -a logs/${VERSION}/dse2.log &
    vagrant provision dse3 | tee -a logs/${VERSION}/dse3.log &
    vagrant provision dse4 | tee -a logs/${VERSION}/dse4.log &

    jobs
    wait
unset SPARK
export SOLR=1
    vagrant provision dse5 | tee -a logs/${VERSION}/dse5.log
    vagrant provision dse6 | tee -a logs/${VERSION}/dse6.log &
    vagrant provision dse7 | tee -a logs/${VERSION}/dse7.log &
    vagrant provision dse8 | tee -a logs/${VERSION}/dse8.log &
    vagrant provision dse9 | tee -a logs/${VERSION}/dse9.log &

    jobs
    wait
unset SOLR

vagrant provision opscenter | tee -a logs/${VERSION}/opscenter.log &
vagrant provision demo | tee -a logs/${VERSION}/demo.log &

jobs
wait

# gather web ports
export WEB_PORT=1
OPSCENTER_PORT=$(vagrant provision opscenter | grep WEB_PORT | awk '{print $4}')
DEMO_PORT=$(vagrant provision demo | grep WEB_PORT | awk '{print $4}')
unset WEB_PORT

# display urls
OPSCENTER_PUBLIC_HOST=$(vagrant ssh-config opscenter | grep HostName | awk '{print $2}')
DEMO_PUBLIC_HOST=$(vagrant ssh-config demo | grep HostName | awk '{print $2}')
echo -e "OpsCenter address: \n    http://${OPSCENTER_PUBLIC_HOST}:${OPSCENTER_PORT}"
echo -e "Demo address: \n    http://${DEMO_PUBLIC_HOST}:${DEMO_PORT}"
